apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rating-service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rating-service
    spec:
      containers:
        - name: rating-service-container
          image: {{ .Values.docker_registry }}/rating-service
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 150Mi
            limits:
              cpu: 300m
              memory: 300Mi
