apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: {{ .Values.docker_registry }}/{{ .Chart.Name }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 250Mi
            limits:
              cpu: 1100m
              memory: 400Mi
          env:
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz-system.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: SERVICE_STREAM_NAME
              value: {{ .Values.rating_service_stream_name }}
            - name: SERVICE_CONSUMER_NAME
              value: {{ .Values.rating_service_consumer_name }}
            - name: DATABASE_POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: username
            - name: DATABASE_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: password
            - name: DATABASE_POSTGRESQL_DATABASENAME
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: dbname


