apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rating-service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rating-service
    spec:
      containers:
        - name: rating-service-container
          image: {{ .Values.docker_registry }}/rating-service
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 250Mi
            limits:
              cpu: 800m
              memory: 400Mi
          env:
            - name: SERVICE_STREAM_NAME
              value: {{ .Values.rating_service_stream_name }}
            - name: SERVICE_CONSUMER_NAME
              value: {{ .Values.rating_service_consumer_name }}
            - name: DATABASE_POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: host
            - name: DATABASE_POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: username
            - name: DATABASE_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: password
            - name: DATABASE_POSTGRESQL_DATABASENAME
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: dbname


