apiVersion: v1
kind: Service
metadata:
  name: http-to-nats-proxy-service
spec:
  selector:
    app.kubernetes.io/name: http-to-nats-proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: service-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-to-nats-proxy-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-to-nats-proxy
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-to-nats-proxy
    spec:
      containers:
        - name: http-to-nats-proxy-container
          image: {{ .Values.docker_registry }}/http-to-nats-proxy
          imagePullPolicy: Always
          ports:
            - name: service-port
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 70Mi
            limits:
              cpu: 300m
              memory: 200Mi
          env:
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz-system.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
