using System;
using System.Collections.Generic;
using System.Linq;
using ByteBard.AsyncAPI.Models;
using Microsoft.CodeAnalysis;

namespace AsyncApiBindingsGenerator
{
    internal static class OutputGenerator
    {
        public static (string source, string className) GenerateSpecOutputs(AsyncApiDocument spec, INamedTypeSymbol mainClassSymbol)
        {
            var @namespace = mainClassSymbol.ContainingNamespace.ToDisplayString();
            var serviceNamespacePart = @namespace.Split('.').First();
            var channels = spec.Channels;
            var addresses = channels.Select(channel => channel.Value.Address);
            var splitAddresses = addresses.Select(address =>
            {
                var parts = address.Split('.');
                return (parts.First(), parts.ElementAt(1));
            });

            var formattedDependencies = splitAddresses.Select(((string restMethod, string pathPart) addressInfo) =>
            {
                var interfaceName = $"I{ToPascalCase(addressInfo.restMethod)}{ToPascalCase(addressInfo.pathPart)}Handler";
                var variableName = $"{addressInfo.restMethod}{ToPascalCase(addressInfo.pathPart)}Handler";
                return $"{interfaceName} {variableName}";
            });

            var formattedCases = splitAddresses.Select(((string restMethod, string pathPart) addressInfo) =>
            {
                var variableName = $"{addressInfo.restMethod}{ToPascalCase(addressInfo.pathPart)}Handler";
                var methodName = GetCaseMethodName(addressInfo.restMethod);
                return $@"            case (""{addressInfo.restMethod}"", ""{addressInfo.pathPart}""):
                await {methodName}(client, message, {variableName}, cancellationToken);
                break;";
            });

            var source =
$@"// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using NATS.Client.JetStream;
using NATS.Net;
using {serviceNamespacePart}.Application.Handlers;

namespace {@namespace};

internal partial class MainHandler({string.Join(", ", formattedDependencies)})
{{
    private async Task DispatchRequest(NatsClient client, (string httpMethod, string pathPart) splitSubject, NatsJSMsg<Request<JsonNode>> message, CancellationToken cancellationToken)
    {{
        switch (splitSubject)
        {{
{string.Join(@"
", formattedCases)}
        }}
    }}
}}
";

            return (source, "MainHandler.DispatchRequest");
        }

        private static string GetCaseMethodName(string restMethod)
        {
            switch (restMethod.ToLower())
            {
                case "get":
                    return "HandleGet";
                case "post":
                    return "HandlePost";
                case "put":
                    return "HandlePut";
                case "delete":
                    return "HandleDelete";
                case "patch":
                    return "HandlePatch";
                default:
                    throw new ArgumentException($"Unsupported REST method: {restMethod}");
            }
        }

        private static string ToPascalCase(string input)
        {
            return $"{char.ToUpper(input[0])}{input.Substring(1)}";
        }
    }
}