apiVersion: batch/v1
kind: Job
metadata:
  name: rating-service-database-migration-job
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.docker_registry }}/rating-service-database-migration-job
        imagePullPolicy: Always
        env:
          - name: DATABASE_POSTGRESQL_HOST
            valueFrom:
              secretKeyRef:
                name: cluster-example-app
                key: host
          - name: DATABASE_POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: cluster-example-app
                key: username
          - name: DATABASE_POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cluster-example-app
                key: password
          - name: DATABASE_POSTGRESQL_DATABASENAME
            valueFrom:
              secretKeyRef:
                name: cluster-example-app
                key: dbname
