apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: service-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.docker_registry }}/frontend
          imagePullPolicy: Always
          ports:
            - name: service-port
              containerPort: 3000
          env:
            - name: RATING_SERVICE_URL_BASE
              value: {{ .Values.RATING_SERVICE_URL_BASE }}
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
