apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: service-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.docker_registry }}/frontend
          imagePullPolicy: Always
          ports:
            - name: service-port
              containerPort: 8000
          env:
            - name: RATING_SERVICE_URL_BASE
              value: {{ .Values.RATING_SERVICE_URL_BASE }}/ratings
            - name: RATING_SERVICE_URL_BASE_SERVERSIDE
              value: "http://$(HTTP_TO_NATS_PROXY_SERVICE_SERVICE_HOST):$(HTTP_TO_NATS_PROXY_SERVICE_SERVICE_PORT)/ratings"
            - name: APP_URL_BASE_PATH
              value: "/ui"
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 500Mi

