// <auto-generated/>
#nullable restore

using FluentValidation;
using TestProject.Application.Queries;

namespace TestProject.Api.Validators;

internal class DeleteRatingsQueryValidator : AbstractValidator<DeleteRatingsQuery>
{
    public DeleteRatingsQueryValidator()
    {
        
    }
}
