// <auto-generated/>
#nullable restore

using FluentValidation;
using TestProject.Application.Commands;

namespace TestProject.Api.Validators;

internal class DeleteRatingsCommandValidator : AbstractValidator<DeleteRatingsCommand>
{
    public DeleteRatingsCommandValidator()
    {
        
    }
}
