// <auto-generated/>
#nullable restore

using FluentValidation;
using TestProject.Application.Queries;

namespace TestProject.Api.Validators;

internal class GetRatingsQueryValidator : AbstractValidator<GetRatingsQuery>
{
    public GetRatingsQueryValidator()
    {
        
    }
}
