//// <auto-generated/>
//#nullable restore

//using System.Text.Json.Nodes;
//using NATS.Client.JetStream;
//using NATS.Net;
//using Service.Api.Common;
//using TestProject.Application.Handlers;

//namespace TestProject;

//public class RequestDispatcher(IRestHandler restHandler, IGetRatingsHandler getUsersHandler, IPostRatingsHandler postUsersHandler) : IRequestDispatcher
//{
//    public async Task DispatchRequest(NatsClient client, (string httpMethod, string pathPart) splitSubject, string[] pathParts, INatsJSMsg<Request<JsonNode>> message, CancellationToken cancellationToken)
//    {
//        switch (splitSubject)
//        {
//            case ("get", "ratings"):
//                await restHandler.HandleGet(client, message, pathParts, getUsersHandler, mergeGetRatings, cancellationToken);
//                break;
//            case ("post", "ratings"):
//                await restHandler.HandlePost(client, message, pathParts, postUsersHandler, mergePostRatings, cancellationToken);
//                break;
//        }
//    }

//    private static GetRatingsQuery mergeGetRatings(GetRatingsQuery original, string[] pathParts)
//    {
//        return original with { Id = int.Parse(pathParts[0]) };
//    }

//    private static PostRatingsCommand mergePostRatings(PostRatingsCommand original, string[] pathParts)
//    {
//        return original with { Id = int.Parse(pathParts[0]) };
//    }
//}
