// <auto-generated/>
#nullable restore

using FluentValidation;
using TestProject.Application.Commands;

namespace TestProject.Api.Validators;

internal class PostRatingsCommandValidator : AbstractValidator<PostRatingsCommand>
{
    public PostRatingsCommandValidator()
    {
        RuleForEach(x => x.Items).SetValidator(new RatingValidator());
    }
}
