// <auto-generated/>
#nullable restore

using FluentValidation;
using TestProject.Application.Models;

namespace TestProject.Api.Validators;

internal class RatingValidator : AbstractValidator<Rating>
{
    public RatingValidator()
    {
        RuleFor(x => x.Score).GreaterThanOrEqualTo(0).LessThanOrEqualTo(5);
    }
}
