// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using NATS.Net;
using Service.Api.Common;
using TestProject.Application.Handlers;

namespace TestProject;

public class RequestDispatcher(IRestHandler restHandler, IGetRatingsHandler getRatingsHandler, IPostRatingsHandler postRatingsHandler, IDeleteRatingsHandler deleteRatingsHandler) : IRequestDispatcher
{
    public async Task DispatchRequest(NatsClient client, string[] pathParts, Request<JsonNode> requestData, CancellationToken cancellationToken)
    {
        switch (pathParts)
        {
            case ["get", "ratings"]:
                await restHandler.HandleGet(client, requestData, pathParts, getRatingsHandler, mergeGetRatings, cancellationToken);
                break;
            case ["post", "ratings"]:
                await restHandler.HandlePost(client, requestData, pathParts, postRatingsHandler, mergePostRatings, cancellationToken);
                break;
            case ["delete", "ratings"]:
                await restHandler.HandleDelete(client, requestData, pathParts, deleteRatingsHandler, mergeDeleteRatings, cancellationToken);
                break;
        }
    }

    private static TestProject.Application.Queries.GetRatingsQuery mergeGetRatings(TestProject.Application.Queries.GetRatingsQuery original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        return original with
        {
            Ids = queryParameters.TryGetValue("ids", out var ids)
                ? ids.Split(",").Select(Guid.Parse)
                : original.Ids,
        };
    }

    private static TestProject.Application.Commands.PostRatingsCommand mergePostRatings(TestProject.Application.Commands.PostRatingsCommand original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        return original;
    }

    private static TestProject.Application.Queries.DeleteRatingsQuery mergeDeleteRatings(TestProject.Application.Queries.DeleteRatingsQuery original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        return original with
        {
            Ids = queryParameters.TryGetValue("ids", out var ids)
                ? ids.Split(",").Select(Guid.Parse)
                : original.Ids,
        };
    }
}
