// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using NATS.Client.JetStream;
using NATS.Net;
using Service.Api.Common;
using TestProject.Application.Handlers;

namespace TestProject;

public class RequestDispatcher(IRestHandler restHandler, IGetRatingsHandler getRatingsHandler, IPostRatingsHandler postRatingsHandler) : IRequestDispatcher
{
    public async Task DispatchRequest(NatsClient client, (string httpMethod, string pathPart) splitSubject, string[] pathParts, INatsJSMsg<Request<JsonNode>> message, CancellationToken cancellationToken)
    {
        switch (splitSubject)
        {
            case ("get", "ratings"):
                await restHandler.HandleGet(client, message, pathParts, getRatingsHandler, cancellationToken);
                break;
            case ("post", "ratings"):
                await restHandler.HandlePost(client, message, pathParts, postRatingsHandler, mergePostRatings, cancellationToken);
                break;
        }
    }

    private static TestProject.Application.Commands.PostRatingsCommand mergePostRatings(TestProject.Application.Commands.PostRatingsCommand original, string[] pathParts)
    {
        return original;
    }
}
