// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using NATS.Net;
using Service.Api.Common;
using TestProject.Application.Handlers;

namespace TestProject;

public class RequestDispatcher(IRestHandler restHandler, IQueryParameterParser queryParameterParser, IGetRatingsHandler getRatingsHandler, IPostRatingsHandler postRatingsHandler, IDeleteRatingsHandler deleteRatingsHandler) : IRequestDispatcher
{
    public async Task DispatchRequest(NatsClient client, string[] pathParts, Request<JsonNode> requestData, CancellationToken cancellationToken)
    {
        switch (pathParts)
        {
            case ["get", "ratings"]:
                await restHandler.HandleGet(client, requestData, pathParts, getRatingsHandler, mergeGetRatings, cancellationToken);
                break;
            case ["post", "ratings"]:
                await restHandler.HandlePost(client, requestData, pathParts, postRatingsHandler, mergePostRatings, cancellationToken);
                break;
            case ["delete", "ratings"]:
                await restHandler.HandleDelete(client, requestData, pathParts, deleteRatingsHandler, mergeDeleteRatings, cancellationToken);
                break;
        }
    }

    private (TestProject.Application.Queries.GetRatingsQuery, IEnumerable<ValidationError>) mergeGetRatings(TestProject.Application.Queries.GetRatingsQuery original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        var errors = Enumerable.Empty<ValidationError>();
        var merged = original;

        var (ids, idsErrors) = queryParameterParser.ParseGuid(original.Ids, queryParameters, "ids");

        if (!idsErrors.Any())
        {
            merged = original with
            {
                Ids = ids,
            };
        }
        else
        {
            errors = errors
                .Concat(idsErrors);
        }

        return (merged, errors);
    }

    private (TestProject.Application.Commands.PostRatingsCommand, IEnumerable<ValidationError>) mergePostRatings(TestProject.Application.Commands.PostRatingsCommand original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        var errors = Enumerable.Empty<ValidationError>();
        var merged = original;

        return (merged, errors);
    }

    private (TestProject.Application.Queries.DeleteRatingsQuery, IEnumerable<ValidationError>) mergeDeleteRatings(TestProject.Application.Queries.DeleteRatingsQuery original, Dictionary<string, string> queryParameters, string[] pathParts)
    {
        var errors = Enumerable.Empty<ValidationError>();
        var merged = original;

        var (ids, idsErrors) = queryParameterParser.ParseGuid(original.Ids, queryParameters, "ids");

        if (!idsErrors.Any())
        {
            merged = original with
            {
                Ids = ids,
            };
        }
        else
        {
            errors = errors
                .Concat(idsErrors);
        }

        return (merged, errors);
    }
}
