// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using Microsoft.Extensions.DependencyInjection;
using Service.Api.Common;
using TestProject.Application.Commands;
using TestProject.Application.Queries;
using TestProject.Application.QueryResponses;

namespace TestProject;

internal static class ResponseStrategiesExtensions
{
    public static IServiceCollection AddResponseStrategies(this IServiceCollection services)
    {
        services.AddScoped<IResponseStrategy<GetRatingsQuery, GetRatingsQueryResponse>, GetResponseStrategy<GetRatingsQuery, GetRatingsQueryResponse>>();
        services.AddScoped<IResponseStrategy<PostRatingsCommand, JsonObject>, PostResponseStrategy<PostRatingsCommand, JsonObject>>();
        services.AddScoped<IResponseStrategy<DeleteRatingsCommand, JsonObject>, DeleteResponseStrategy<DeleteRatingsCommand, JsonObject>>();

        return services;
    }
}
