// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using Service.Api.Common;
using TestProject.Api.Validators;
using TestProject.Application.Commands;
using TestProject.Application.Models;
using TestProject.Application.Queries;
using TestProject.Application.QueryResponses;

namespace TestProject;

internal static class ValidationExtensions
{
    public static IServiceCollection AddValidators(this IServiceCollection services)
    {
        services.AddSingleton<IValidator<GetRatingsQuery>, GetRatingsQueryValidator>();
        services.AddSingleton<IValidator<PostRatingsCommand>, PostRatingsCommandValidator>();
        services.AddSingleton<IValidator<Rating>, RatingValidator>();
        services.AddSingleton<IValidator<DeleteRatingsQuery>, DeleteRatingsQueryValidator>();

        return services;
    }
}
