using System;
using System.Collections.Generic;
using System.Linq;
using ByteBard.AsyncAPI.Models;
using Microsoft.CodeAnalysis;

namespace AsyncApiBindingsGenerator
{
    internal static class OutputGenerator
    {
        public static (string source, string className) GenerateSpecOutputs(AsyncApiDocument spec, string assemblyName)
        {
            var @namespace = assemblyName;
            var serviceNamespacePart = @namespace.Split('.').First();
            var channels = spec.Channels;
            var addresses = channels.Select(channel => channel.Value.Address);
            var splitAddresses = addresses.Select(address =>
            {
                var parts = address.Split('.');
                return (parts.First(), parts.ElementAt(1));
            });

            var firstDependency = new List<string>() { "IRestHandler restHandler" };
            var formattedDependencies = firstDependency.Concat(splitAddresses.Select(((string restMethod, string pathPart) addressInfo) =>
            {
                var interfaceName = $"I{ToPascalCase(addressInfo.restMethod)}{ToPascalCase(addressInfo.pathPart)}Handler";
                var variableName = $"{addressInfo.restMethod}{ToPascalCase(addressInfo.pathPart)}Handler";
                
                return $"{interfaceName} {variableName}";
            }));

            var formattedCases = channels.Select(channel =>
            {
                var messageReference = channel.Value.Messages.First().Value;
                var messageBodyExistsString = GetType(spec, messageReference, string.Empty, "X");
                var IsmessageBodyExists = messageBodyExistsString != string.Empty;

                var address = channel.Value.Address;
                var addressParts = address.Split('.');
                var restMethod = addressParts.First();
                var pathPart = addressParts.ElementAt(1);

                var pathPartsFormatted = string.Join(", ", addressParts.Select(p => $@"""{p}"""));

                var variableName = $"{restMethod}{ToPascalCase(pathPart)}Handler";
                var methodName = GetCaseMethodName(restMethod);
                var mergeMethodName = $"merge{ToPascalCase(restMethod)}{ToPascalCase(pathPart)}";
                var mergeMethodNameWithComma = IsmessageBodyExists
                    ? $"{mergeMethodName}, "
                    : string.Empty;

                return $@"            case [{pathPartsFormatted}]:
                await restHandler.{methodName}(client, requestData, pathParts, {variableName}, {mergeMethodNameWithComma}cancellationToken);
                break;";
            });

            var formattedMergeMethods = channels.Select(channel =>
            {
                var messageReference = channel.Value.Messages.First().Value;
                var messageBodyExistsString = GetType(spec, messageReference, string.Empty, "X");
                var IsmessageBodyExists = messageBodyExistsString != string.Empty;

                string result;

                if (IsmessageBodyExists)
                {
                    var address = channel.Value.Address;
                    var parts = address.Split('.');
                    var restMethod = parts.First();
                    var pathPart = parts.ElementAt(1);

                    var requestType = GetRequestType(restMethod);
                    var mergeTypeNamespace = GetMergeTypeNamespace(restMethod, serviceNamespacePart);
                    var mergeType = $"{mergeTypeNamespace}.{ToPascalCase(restMethod)}{ToPascalCase(pathPart)}{requestType}";
                    var mergeMethodName = $"merge{ToPascalCase(restMethod)}{ToPascalCase(pathPart)}";

                    result = $@"    private static {mergeType} {mergeMethodName}({mergeType} original, string[] pathParts)
    {{
        return original;
    }}";
                } else
                {
                    result = string.Empty;
                }

                return result;
            })
                .Where(m => m != string.Empty);

            var source =
$@"// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using NATS.Net;
using Service.Api.Common;
using {serviceNamespacePart}.Application.Handlers;

namespace {@namespace};

public class RequestDispatcher({string.Join(", ", formattedDependencies)}) : IRequestDispatcher
{{
    public async Task DispatchRequest(NatsClient client, string[] pathParts, Request<JsonNode> requestData, CancellationToken cancellationToken)
    {{
        switch (pathParts)
        {{
{string.Join(@"
", formattedCases)}
        }}
    }}

{string.Join(@"

", formattedMergeMethods)}
}}
";

            return (source, "RequestDispatcher");
        }

        private static string GetType(AsyncApiDocument spec, AsyncApiMessage messageReference, string noBodyValue, string hasBodyValue)
        {
            KeyValuePair<string, AsyncApiJsonSchema> bodyEntry = GetBodyEntry(messageReference);

            if (bodyEntry.Equals(default(KeyValuePair<string, AsyncApiJsonSchema>)))
            {
                return noBodyValue;
            }

            return hasBodyValue;
        }

        private static KeyValuePair<string, AsyncApiJsonSchema> GetBodyEntry(AsyncApiMessage messageReference)
        {
            return messageReference
                .Payload.Schema.As<AsyncApiJsonSchema>()
                .Properties.FirstOrDefault(prop => prop.Key == "body");
        }

        private static string GetRequestType(string restMethod)
        {
            switch (restMethod)
            {
                case "get":
                    return "Query";
                case "post":
                    return "Command";
                default:
                    throw new ArgumentException($"Rest method '{restMethod}' not supported.");
            }
        }

        private static string GetCaseMethodName(string restMethod)
        {
            switch (restMethod.ToLower())
            {
                case "get":
                    return "HandleGet";
                case "post":
                    return "HandlePost";
                case "put":
                    return "HandlePut";
                case "delete":
                    return "HandleDelete";
                case "patch":
                    return "HandlePatch";
                default:
                    throw new ArgumentException($"Unsupported REST method: {restMethod}");
            }
        }

        private static string GetMergeTypeNamespace(string restMethod, string assemblyName)
        {
            switch (restMethod)
            {
                case "get":
                    return $"{assemblyName}.Application.Queries";
                case "post":
                    return $"{assemblyName}.Application.Commands";
                default:
                    throw new ArgumentException($"Rest method '{restMethod}' not supported.");
            }
        }

        private static string ToPascalCase(string input)
        {
            return $"{char.ToUpper(input[0])}{input.Substring(1)}";
        }
    }
}