// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Queries;

public readonly struct DeleteRatingsQuery()
{
    [JsonPropertyName("ids")]
    public IEnumerable<int> Ids { get; init; } = new List<int>();
}
