// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Commands;

public readonly record struct DeleteRatingsCommand()
{
    [JsonPropertyName("ids")]
    public IEnumerable<Guid> Ids { get; init; } = new List<Guid>();
}
