// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.QueryResponses;

public readonly struct GetRatingsQueryResponse
{
    [JsonPropertyName("items")]
    public IEnumerable<TestProject.Models.Rating> Items { get; init; }
}
