// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.QueryResponses;

public readonly struct GetUsersQueryResponse
{
    [JsonPropertyName("items")]
    public TestProject.Models.User[] Items { get; init; }
}
