// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IDeleteRatingsHandler : IHandler<TestProject.Commands.DeleteRatingsCommand>
{
}
