// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IDeleteRatingsHandler : IDeleteHandler<TestProject.Queries.DeleteRatingsQuery>
{
}
