// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IGetRatingsHandler : IGetHandler<TestProject.Queries.GetRatingsQuery, TestProject.QueryResponses.GetRatingsQueryResponse>
{
}
