// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IGetUsersHandler : IGetHandler<TestProject.QueryResponses.GetUsersQueryResponse>
{
}
