// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IPostRatingsHandler : IPostHandler<TestProject.Commands.PostRatingsCommand>
{
}
