// <auto-generated/>
#nullable restore

using Service.Application.Common.Handlers;

namespace TestProject.Handlers;

public interface IPostUsersHandler : IPostHandler<TestProject.Commands.PostUsersCommand, string>
{
}
