// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Commands;

public readonly struct PostRatingsCommand()
{
    [JsonPropertyName("items")]
    public IEnumerable<TestProject.Models.Rating> Items { get; init; } = new List<TestProject.Models.Rating>();
}
