// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Commands;

public readonly struct PostUsersCommand
{
    [JsonPropertyName("items")]
    public IEnumerable<TestProject.Models.User> Items { get; init; }
}
