// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Models;

public readonly struct Rating()
{
    [JsonPropertyName("id")]
    public int Id { get; init; }

    [JsonPropertyName("userId")]
    public int UserId { get; init; }

    [JsonPropertyName("serviceId")]
    public int ServiceId { get; init; }

    [JsonPropertyName("score")]
    public int Score { get; init; }
}
