// <auto-generated/>
#nullable restore

using System.Text.Json.Serialization;

namespace TestProject.Models;

public readonly struct User
{
    [JsonPropertyName("id")]
    public int Id { get; init; }

    [JsonPropertyName("username")]
    public string Username { get; init; }
}
