apiVersion: batch/v1
kind: Job
metadata:
  name: rating-service-redis-setup-job
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.docker_registry }}/rating-service-redis-setup-job
        imagePullPolicy: Always
