apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .Values.rating_service_stream_name }}
spec:
  name: {{ .Values.rating_service_stream_name }}
  subjects: ["*.services", "*.users", "*.ratings"]
  storage: memory
  maxAge: 1h
  noAck: true

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: {{ .Values.rating_service_consumer_name }}
spec:
  streamName: {{ .Values.rating_service_stream_name }}
  durableName: {{ .Values.rating_service_consumer_name }}
  deliverPolicy: all
  # filterSubjects: ["*.services", "*.users", "*.ratings"]
  maxDeliver: 20
  ackPolicy: explicit
