apiVersion: gateway.solo.io/v1
kind: VirtualHostOption
metadata:
  name: header-manipulation
  namespace: gloo-system
spec:
  options:
    cors:
      allowOrigin:
        - "*"
      allowMethods:
        - "*"
      allowHeaders:
        - "*"
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http
      namespace: gloo-system
