apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http
  namespace: gloo-system
spec:
  gatewayClassName: gloo-gateway
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rating-service-route
  namespace: default
spec:
  parentRefs:
    - name: http
      namespace: gloo-system
  rules:
    - matches:
        - path:
            value: "/api"
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.solo.io
            kind: RouteOption
            name: rewrite
      backendRefs:
        - name: http-to-nats-proxy-service
          port: 8080

---
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: rewrite
  namespace: default
spec:
  options:
    regexRewrite:
      pattern:
        regex: "/api"
      substitution: ""
