apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: mystream
spec:
  name: mystream
  subjects: ["*.services", "*.users", "*.ratings"]
  storage: memory
  maxAge: 1h
  noAck: true

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: my-pull-consumer
spec:
  streamName: mystream
  durableName: my-pull-consumer
  deliverPolicy: all
  # filterSubjects: ["*.services", "*.users", "*.ratings"]
  maxDeliver: 20
  ackPolicy: explicit
