apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  resources:
    requests:
      cpu: 500m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 400Mi
  storage:
    size: 1Gi