docker_registry: ratingserviceclusterregistry.azurecr.io
docker_registry_name: ratingserviceclusterregistry.azurecr.io
http_to_nats_build_directory: https://github.com/CodingFlow/http-to-nats-proxy.git#main
