apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: redis-container
          image: {{ .Values.docker_registry }}/redis
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
