// <auto-generated/>
#nullable restore

using System.Text.Json.Nodes;
using Microsoft.Extensions.DependencyInjection;
using Service.Api.Common;
using TestProject.Application.Commands;
using TestProject.Application.Queries;
using TestProject.Application.QueryResponses;

namespace TestProject;

internal static class RequestDecoratorExtensions
{
    public static IServiceCollection AddRequestDecorators(this IServiceCollection services)
    {
        services.Decorate<IResponseStrategy<GetRatingsQuery, GetRatingsQueryResponse>, TestProject.RequestDecorator<GetRatingsQuery, GetRatingsQueryResponse>>();
        services.Decorate<IResponseStrategy<PostRatingsCommand, JsonObject>, TestProject.RequestDecorator<PostRatingsCommand, JsonObject>>();
        services.Decorate<IResponseStrategy<DeleteRatingsCommand, JsonObject>, TestProject.RequestDecorator<DeleteRatingsCommand, JsonObject>>();

        return services;
    }
}
